name: Saxon-9 XML Transformation

on:
  push:
    paths:
      - '**.xml'
      - '**.xslt'
      - '.github/workflows/main.yml'

jobs:
  saxon-transformation:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Java (Saxon benötigt Java)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Download Saxon-HE 9.9 source
        run: |
          mkdir saxon-src
          wget -O saxon.zip https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE12-5/SaxonHE12-5J.zip
          unzip saxon.zip -d saxon-src

      - name: Compile Saxon
        run: |
          cd saxon-src

      # Führe die XML-Transformation durch
      - name: Run Saxon transformation
        run: |
          java -cp saxon-src/saxon-he-12.5.jar \
            -s:input.xml -xsl:transform.xsl -o:output.xml

      # Optional: Lade das Ergebnis hoch (z. B. als Artefakt)
      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: transformed-xml
          path: output.xml
