name: Saxon-9 XML Transformation

on:
  push:
    branches:
      - '**.xml'
      - '**.xslt'
      - '.github/workflows/saxon-transformation.yml'

jobs:
  saxon-transformation:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Java (Saxon benötigt Java)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Download Saxon-HE 9.9 source
        run: |
          mkdir saxon-src
          wget -O saxon.zip https://github.com/Saxonica/Saxon-Archive/raw/main/Saxon-HE/9/9.9/saxon9-9-1-8source.zip
          unzip saxon.zip -d saxon-src

      - name: Compile Saxon
        run: |
          cd saxon-src
          mkdir build
          find . -name "*.java" > sources.txt
          javac -d build @sources.txt

      # Führe die XML-Transformation durch
      - name: Run Saxon transformation
        run: |
          java -cp saxon-src/build net.sf.saxon.Transform \
            -s:input.xml -xsl:transform.xsl -o:output.xml

      # Optional: Lade das Ergebnis hoch (z. B. als Artefakt)
      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: transformed-xml
          path: output.xml
