name: Saxon-9 XML Transformation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  saxon-transformation:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Java (Saxon benötigt Java)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      # Install Saxon-HE 9
      - name: Install Saxon-HE 9
        run: |
          wget https://github.com/Saxon-Project/Saxon/releases/download/Saxon-HE-9.9/saxon-he-9.9.1-8.jar -O /usr/local/bin/saxon9.jar
          chmod +x /usr/local/bin/saxon9.jar

      # Führe die XML-Transformation durch
      - name: Run Saxon transformation
        run: |
          java -jar /usr/local/bin/saxon9.jar -s:input.xml -xsl:transform.xsl -o:output.xml

      # Optional: Lade das Ergebnis hoch (z. B. als Artefakt)
      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: transformed-xml
          path: output.xml
